NEIGHBORHOODS = [
    "Agronomia", "Almagro", "Balvanera", "Barracas", "Belgrano", "Boedo", "Caballito", "Chacarita",
    "Coghlan", "Colegiales", "Constitucion", "Flores", "Floresta", "Boca", "Paternal", "Liniers",
    "Mataderos", "Monte Castro", "Montserrat", "Nueva Pompeya", "Nuñez", "Palermo", "Parque Avellaneda",
    "Parque Chacabuco", "Parque Chas", "Parque Patricios", "Puerto Madero", "Recoleta", "Retiro",
    "Saavedra", "San Cristobal", "San Nicolas", "San Telmo", "Versalles", "Villa Crespo", "Villa Devoto",
    "Villa General Mitre", "Villa Lugano", "Villa Luro", "Villa Ortuzar", "Villa Pueyrredon", "Villa Real",
    "Villa Riachuelo", "Villa Santa Rita", "Villa Soldati", "Villa Urquiza", "Villa del Parque", "Velez Sarsfield"
]
PROPERTY_TYPES = ["departamento", "casa", "PH"]
CALLES = [
    "Av. 9 de Julio", "Av. 27 de Febrero", "Av. Achával Rodríguez", "Av. Acoyte", "Av. Albarellos",
    "Av. Almirante Brown", "Av. Alsina", "Av. Álvarez Jonte", "Av. Álvarez Thomas", "Av. Alvear",
    "Av. Antártida Argentina", "Av. Asamblea", "Av. Asturias", "Av. Avellaneda", "Av. Balbín",
    "Av. Beiró", "Av. Belgrano", "Av. Berro", "Av. Bilbao", "Av. Boedo", "Av. Bonorino",
    "Av. Boyacá", "Av. Brasil", "Av. Bruix", "Av. Burmeister", "Av. Callao", "Av. Campos",
    "Av. Carabobo", "Av. Casares", "Av. Caseros", "Av. Castañares", "Av. Castillo", "Av. Castro Barros",
    "Av. Chiclana", "Av. Cobo", "Av. Congreso", "Av. Constituyentes", "Av. Córdoba", "Av. de los Incas",
    "Av. del Campo", "Av. del Libertador", "Av. Diaz Velez", "Av. Dorrego", "Av. Elcano",
    "Av. Entre Ríos", "Av. Escalada", "Av. Estado de Israel", "Av. Eva Perón", "Av. Figueroa Alcorta",
    "Av. Federico Lacroze", "Av. Gaona", "Av. Garay", "Av. General Paz", "Av. Goyena",
    "Av. Honorio Pueyrredón", "Av. Huergo", "Av. Independencia", "Av. Infanta Isabel", "Av. Iriarte",
    "Av. Juan B. Justo", "Av. Juan de Garay", "Av. Jujuy", "Av. Juramento", "Av. La Plata",
    "Av. Larrazábal", "Av. Las Heras", "Av. Leandro N. Alem", "Av. Lope de Vega", "Av. Manuel Rodríguez",
    "Av. Mayo", "Av. Medrano", "Av. Monroe", "Av. Montes de Oca", "Av. Mosconi", "Av. Nazca",
    "Av. Olivera", "Av. Ortiz de Ocampo", "Av. Padilla", "Av. Patricios", "Av. Pavón",
    "Av. Pedro de Mendoza", "Av. Perito Moreno", "Av. Pueyrredón", "Av. Quintana", "Av. Regimiento de Patricios",
    "Av. Rivadavia", "Av. Roca", "Av. Roque Sáenz Peña", "Av. Sáenz", "Av. Salvador María del Carril",
    "Av. San Juan", "Av. San Martín", "Av. Santa Fe", "Av. Sarmiento", "Av. Scalabrini Ortiz",
    "Av. Triunvirato", "Av. Varela", "Av. Warnes",
    "Acassuso", "Acevedo", "Acha", "Achala", "Achával", "Achega", "Acosta", "Acuña de Figueroa",
    "Agaces", "Agote", "Agrelo", "Aguado", "Aguaribay", "Agüero", "Aguilar", "Aguirre",
    "Aizpurúa", "Alagón", "Albariño", "Albarracín", "Alberti", "Alcaraz", "Alemania", "Algarrobo",
    "Alicante", "Allende", "Almagro", "Alpatacal", "Alta Gracia", "Altolaguirre", "Alvarado",
    "Álvarez Prado", "Amambay", "Amberes", "Ameghino", "Amsterdam", "Anasagasti", "Anchorena",
    "Anchoris", "Ancón", "Andalgalá", "Andalucía", "Andonaegui", "Andorra", "Andrade", "Angaco",
    "Ankara", "Antequera", "Antezana", "Antofagasta", "Añasco", "Apulé", "Aquino", "Aranguren",
    "Aráoz", "Arata", "Araujo", "Arbeletche", "Arcamendia", "Arce", "Arenal", "Arengreen",
    "Argañarás", "Argelia", "Ariel", "Arismendi", "Arizona", "Armenia", "Arolas", "Arquímedes",
    "Arriola", "Arrotea", "Artigas", "Artilleros", "Asunción", "Atahualpa", "Atenas", "Atuel",
    "Ávalos", "Avilés", "Ayolas", "Ayuí", "Azara", "Azcuénaga", "Azopardo", "Azul", "Bach",
    "Bacle", "Bacon", "Bahía", "Bahía Blanca", "Baigorri", "Baigorria", "Baliña", "Ballivián",
    "Baltoré", "Banchs", "Baradero", "Baragaña", "Barcala", "Barcelona", "Barilari", "Bariloche",
    "Barragán", "Barrientos", "Barros Pazos", "Barzana", "Basavilbaso", "Bases", "Basualdo",
    "Bateman", "Bathurst", "Bauness", "Bauzá", "Bavio", "Bazurco", "Beauchef", "Beazley",
    "Becher", "Bedoya", "Beethoven", "Behring", "Beláustegui", "Belén", "Belfast", "Bélgica",
    "Belgrado", "Bell Ville", "Bella Vista", "Bello", "Benedetti", "Berg", "Berlín", "Bermejo",
    "Bermúdez", "Berna", "Bernal", "Bernaldes", "Bernasconi", "Berón de Astrada", "Berthelot",
    "Bertrés", "Betbeder", "Bethlem", "Beyrouth", "Bianchi", "Biarritz", "Bibiloni", "Bidegain",
    "Biedma", "Bielsa", "Billinghurst", "Blandengues", "Blanes", "Blanqueada", "Bocayuva",
    "Boeri", "Bombay", "Bonavena", "Boquerón", "Borches", "Bordabehere", "Bosch", "Bosco",
    "Boston", "Bouchard", "Bragado", "Braille", "Braun Menéndez", "Bravard", "Bravo", "Brin",
    "Brown", "Bruno", "Bruselas", "Bucarest", "Budapest", "Bunge", "Burela", "Buschiazzo",
    "Bynon", "Byron", "Caaguazú", "Cabello", "Cabezón", "Cabot", "Caboto", "Cabral", "Cabred",
    "Cabrer", "Cacheuta", "Cachi", "Cacique", "Cádiz", "Cafayate", "Caffarena", "Cafferata",
    "Cagliari", "Cajaravilla", "Calabria", "Calandra", "Calaza", "Cálcena", "Caldén", "Calfucurá",
    "California", "Calingasta", "Calou", "Calvo", "Calzadilla", "Camacuá", "Cambieses", "Camino",
    "Camoatí", "Campichuelo", "Campillo", "Campos", "Canadá", "Canard", "Cané", "Cangallo",
    "Psj. Acacias", "Psj. Achira", "Psj. Achupallas", "Psj. Aconcagua", "Psj. Aguas Buenas",
    "Psj. Aieta", "Psj. Albania", "Psj. Albarracín de Sarmiento", "Psj. Alfarero", "Psj. El Maestro",
    "Psj. Seaver", "Psj. Giuffra", "Psj. Bollini", "Psj. La Piedad", "Psj. Santamarina"
]
ZONAS = {
    "high": ["Puerto Madero", "Palermo", "Recoleta", "Belgrano", "Nuñez", "Barrio Norte", "Las Cañitas"],
    "midHigh": ["Caballito", "Villa Urquiza", "Colegiales", "Villa Devoto", "Coghlan", "Saavedra", "Chacarita"],
    "mid": ["Almagro", "Villa Crespo", "Villa del Parque", "Boedo", "Parque Chacabuco", "Flores", "San Telmo", "Retiro"],
    "low": ["Villa Lugano", "Villa Soldati", "Nueva Pompeya", "Boca", "Constitucion", "Mataderos", "Liniers"]
  }
